[project]
name = "tejvla"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "bitsandbytes>=0.50.0",
    "lerobot[dataset,training]>=0.6.0",
    "lerobot_policy_babyvla",
    "transformers>=5.14.1",
]

[tool.uv.sources]
lerobot_policy_babyvla = { workspace = true }

[tool.uv.workspace]
members = [
    "policies/lerobot_policy_babyvla",
]


